version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - mongo
    command: ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=8080"]

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/create-db.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: