Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.synced_folder ".", "/vagrant"

config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y

    apt-get install -y nginx

    rm -f /etc/nginx/sites-enabled/default

    cp /vagrant/nginx.conf /etc/nginx/sites-available/my_site
    ln -s /etc/nginx/sites-available/my_site /etc/nginx/sites-enabled/my_site

    cp /vagrant/index.html /var/www/html/index.html

    systemctl restart nginx
SHELL


  config.vm.network "forwarded_port", guest: 80, host: 8016
end
